direction: minimize
gpus_per_task: 0.125
hp:
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 5
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: tanh
    output_act_fn: null
    batch_size: 200
    epochs: 30
    optim:
        w:
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 1e-3
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 1e-4
