direction: minimize
gpus_per_task: 1
hp:
    num_layers: 2
    internal_state_dim: 8
    internal_state_channels:
        sample_type: categorical
        sample_space: [8, 12, 16]
        default: 8
    kernel_size:
        sample_type: categorical
        sample_space: [3, 5, 7]
        default: 5
    batch_size: 500
    epochs: 3
    T:
        sample_type: categorical
        sample_space: [10, 15, 20]
        default: 15
    optim:
        x:
            lr:
                sample_type: categorical
                sample_space: [5e-2, 3e-2, 1e-2, 3e-3]
                default: 3e-2
            momentum:
                sample_type: categorical
                sample_space: [0.0, 0.3, 0.9, 0.99]
                default: None
        w:
            lr:
                sample_type: categorical
                sample_space: [2e-3, 1e-3, 5e-4]
                default: 1e-3
            b1:
                sample_type: categorical
                sample_space: [0.9, 0.95, 0.99]
                default: 0.9
            b2:
                sample_type: categorical
                sample_space: [0.999, 0.9999, 0.99999]
                default: 0.999
