direction: minimize
gpus_per_task: 0.125
dataset_name: cifar10
hp:
    num_layers: 3
    internal_state_dim: 4
    internal_state_channels: 8
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 7
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: tanh
    output_act_fn: null
    batch_size: 200
    epochs: 30
    T: 20
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.012339577360613845
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.1
        w:
            name: adamw
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.0007642161267055484
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 3.511389190873198e-05
            momentum: 0.0
