direction: minimize
gpus_per_task: 0.125
dataset_name: celeba
hp:
    num_layers: 3
    internal_state_dim: 25
    internal_state_channels: 8
    kernel_size:
        sample_type: categorical
        sample_space: [3, 4, 5, 7]
        default: 7
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: hard_tanh
    output_act_fn: null
    batch_size: 200
    epochs: 5
    T:
        sample_type: categorical
        sample_space: [10, 15, 16, 20, 23, 30, 45]
        default: 45
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.2510951818044995
            momentum:
                sample_type: float
                sample_space: [[0.0, 1.0], 0.05]
                default: 0.35
        w:
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.00043196265173594926
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 5.01832572878327e-05
